language: java

cache:
  directories:
    - $HOME/.m2

notifications:
  webhooks: $TEAMS_WEBHOOK

deploy:
  - provider: script
    script: "mvn deploy"
    skip_cleanup: true
    on:
      tags: true
